# Use an official Python image as the base
FROM python:3.10-slim

# Set environment variables to ensure Poetry works as intended
ENV POETRY_VERSION=1.8.1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1

# Install Poetry
RUN pip install --no-cache-dir poetry==$POETRY_VERSION

# Set the working directory in the container
WORKDIR /app

# Copy only the lock files to leverage Docker layer caching
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN poetry install --no-root

# Copy the rest of the application code
COPY . .

# Expose the port Streamlit will use
EXPOSE 8501

# Command to run your Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
